### ISSUE TITLE
No audio on OS X

### ISSUE THREAD

**Issue by haydio** [toru173/Lenkeng373#1]
So glad I found this project before I started my own. I've just tried it on OS X and I'm hoping I'm using it correctly.

I've ran the script then opened the udp://:5010 URL in VLC, I get picture fine, however no audio. Is there something that I'm missing? More that happy to help.

**Comment by toru173** [comment]
Hi Haydio, I haven't tested on OS X recently - I moved my dev setup to Debian a week or so back. I can't remember changing anything in the audio decode path, but I'll look. Can you let me know the args you passed? Not all are supported, currently. Let me know if there's anything you find, or if you can recommend improvements!

**Comment by haydio** [comment]
No worries, I didn't pass any arguments - are there any that you would recommend? at the moment I'm just running "python hdmicap.py.

Thanks again for this awesome script.

**Comment by toru173** [comment]
No worries! Happy to help. Can you describe your setup? What mac, what connections you've made, any adapters you've used or other additional equipment etc.

**Comment by haydio** [comment]
Running on a early 2011 MacBook Pro (15" i7, 4GB RAM). I'm connecting to my switch using the built in gigabit ethernet port (en0).

I have noticed when running the script this line is returned "Guessed Channel Layout for Input Stream #0.0 : stereo"

**Comment by toru173** [comment]
It sounds like you have a very similar setup to my test setup before I deployed to my server. I'll re-test and come back to you. Can you try running again with the --debug argument, and let me know if it gives you any additional information? Perhaps copy and past the output here. Do you get a moving image, or just static? The alert you got is output from FFmpeg, I haven't yet found a way to pass the channel layout

**Comment by haydio** [comment]
Image is fine, and below is the output from when I run with --debug

MacBookPro:hdmicap haydncockayne$ sudo python hdmicap.py --input en0 --receive 192.168.168.55 --debug
Password:
[ Fri May 22 20:01:59 2015 ] Error: File exists
[ Fri May 22 20:01:59 2015 ] Error: File exists
Capturing input on interface en0. Press Ctrl + C to abort
Attempting to open /tmp/audiofifo
Attempting to open /tmp/videofifo
Capturing heartbeat packets on interface en0
ffmpeg version 2.6.2 Copyright (c) 2000-2015 the FFmpeg developers
  built with llvm-gcc 4.2.1 (LLVM build 2336.11.00)
  configuration: --prefix=/Volumes/Ramdisk/sw --enable-gpl --enable-pthreads --enable-version3 --enable-libspeex --enable-libvpx --disable-decoder=libvpx --enable-libmp3lame --enable-libtheora --enable-libvorbis --enable-libx264 --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-libgsm --enable-libvidstab --enable-libx265 --disable-doc --arch=x86_64 --enable-runtime-cpudetect
  libavutil      54. 20.100 / 54. 20.100
  libavcodec     56. 26.100 / 56. 26.100
  libavformat    56. 25.101 / 56. 25.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 11.102 /  5. 11.102
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
Successfully opened /tmp/audiofifo for appending
Capturing audio packets on interface en0
Process Process-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(_self._args, *_self._kwargs)
  File "hdmicap.py", line 283, in parse_packet
    audio_delay_fifo[audio_delay_fifo_write_pointer] = data[16 : ]
IndexError: list assignment index out of range
Guessed Channel Layout for  Input Stream #0.0 : stereo
Input #0, s32be, from '/tmp/audiofifo':
  Duration: N/A, bitrate: 3072 kb/s
    Stream #0:0: Audio: pcm_s32be, 48000 Hz, 2 channels, s32, 3072 kb/s
Successfully opened /tmp/videofifo for appending
Capturing video packets on interface en0
Input #1, mjpeg, from '/tmp/videofifo':
  Duration: N/A, bitrate: N/A
    Stream #1:0: Video: mjpeg, yuvj422p(pc, bt470bg/unknown/unknown), 1920x1080 [SAR 1:1 DAR 16:9], 25 tbr, 1200k tbn, 25 tbc
[swscaler @ 0x7fdc12001600] deprecated pixel format used, make sure you did set range correctly
No pixel format specified, yuv422p for MPEG-2 encoding chosen.
Use -pix_fmt yuv420p for compatibility with outdated media players.
Output #0, mpegts, to 'udp://127.0.0.1:5010?localaddr=10.2.0.201&ttl=1':
  Metadata:
    encoder         : Lavf56.25.101
    Stream #0:0: Video: mpeg2video, yuv422p, 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 200 kb/s, 25 fps, 90k tbn, 25 tbc
    Metadata:
      encoder         : Lavc56.26.100 mpeg2video
    Stream #0:1: Audio: mp2, 48000 Hz, stereo, s16 (32 bit), 384 kb/s
    Metadata:
      encoder         : Lavc56.26.100 mp2
Stream mapping:
  Stream #1:0 -> #0:0 (mjpeg (native) -> mpeg2video (native))
  Stream #0:0 -> #0:1 (pcm_s32be (native) -> mp2 (native))
Press [q] to stop, [?] for help
frame= 4053 fps= 30 q=1.0 size=  403715kB time=00:02:42.04 bitrate=20410.0kbits/s

**Comment by toru173** [comment]
Hi Haydio, audio is now fixed! I have always used it with a delay, so hadn't checked the delay part of the code when no delay is used. I updated some of the code handling arguments too - you can now pass the output string for FFmpeg directly. Please note --receive and --recvmac currently do nothing, and I've updated the args parsing to be more verbose about this. By default the script uses the IP of the receiver connected to the transmitter (en0 in your case) as it doesn't make sense to receive the packets on a different IP. I'm leaving it in there though, as someone might have a specific use case for it.

Let me know how it goes for you now. I'm also curious if you need to delay your audio as well, what CPU usage you see when running the script, and anything else you can tell me!

**Comment by toru173** [comment]
Leaving issue open for now, pending feedback

**Comment by haydio** [comment]
Hi Toru173,

Working perfectly now. Turns out I do need to delay the audio, running "python hdmicap.py --input en0 --delay 100" is working perfectly now.

There is the occasional bit of audio which is dropped, but apart from that it is perfect. CPU is anywhere between 110% and 180%. I was hoping to run this on a RaspberryPi 2 eventually but I don't think that will have the CPU power required.  My end goal is to have the stream setup as a channel in Plex so I can watch PayTV (Foxtel) in all rooms without having to buy additional receivers.

Thanks again
