### ISSUE TITLE
Unable to grab audio stream

### ISSUE THREAD

**Issue by mattcampbellsa** [toru173/Lenkeng373#3]
Hi there,

Thank you for all your hard work, I am able to grab the video stream with minimal effort, however, I've been trying various scripts and still cannot grab the audio

tcpdump does indeed show show traffic on port 2066, however the output of the script doesn't really assist me in finding the issue

matt@matt-ubuntu:~/Lenkeng373/FFmpeg$ sudo python hdmicap.py --input enp3s0f2 --heartbeat --delay 100 -debug 3
Capturing input on interface enp3s0f2. Press Ctrl + C to abort
ffmpeg version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
  configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Guessed Channel Layout for Input Stream #0.0 : stereo
Input #0, s32be, from '/tmp/audiofifo':
  Duration: N/A, bitrate: 3072 kb/s
    Stream #0:0: Audio: pcm_s32be, 48000 Hz, stereo, s32, 3072 kb/s
Input #1, mjpeg, from '/tmp/videofifo':
  Duration: N/A, bitrate: N/A
    Stream #1:0: Video: mjpeg, yuvj422p(pc, bt470bg/unknown/unknown), 1280x540 [SAR 1:1 DAR 64:27], 25 tbr, 1200k tbn, 25 tbc
Stream mapping:
  Stream #1:0 -> #0:0 (mjpeg (native) -> mpeg2video (native))
  Stream #0:0 -> #0:1 (pcm_s32be (native) -> mp2 (native))
Press [q] to stop, [?] for help
[swscaler @ 0x55928ce93ae0] deprecated pixel format used, make sure you did set range correctly
[s32be @ 0x55928cdc6a40] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
Output #0, mpegts, to 'udp://127.0.0.1:5010?ttl=1':
  Metadata:
    encoder         : Lavf57.83.100
    Stream #0:0: Video: mpeg2video (4:2:2), yuv422p(progressive), 1280x540 [SAR 1:1 DAR 64:27], q=2-31, 200 kb/s, 25 fps, 90k tbn, 25 tbc
    Metadata:
      encoder         : Lavc57.107.100 mpeg2video
    Side data:
      cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: -1
    Stream #0:1: Audio: mp2, 48000 Hz, stereo, s16, 384 kb/s
    Metadata:
      encoder         : Lavc57.107.100 mp2
Process Process-3:5 q=1.0 size=  491401kB time=00:02:56.70 bitrate=22781.6kbits/s speed=0.999x    
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
Process Process-4:
av_interleaved_write_frame(): Immediate exit requested
Error writing trailer of udp://127.0.0.1:5010?ttl=1: Immediate exit requested
frame= 4427 fps= 25 q=1.0 Lsize=  492357kB time=00:02:57.00 bitrate=22787.5kbits/s speed=0.999x    
video:447712kB audio:8297kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 7.971106%
Exiting normally, received signal 15.

**Comment by toru173** [comment]
Hi mattcampbellsa,

I'm sorry it's taken me so long to see your request - it appears I didn't have notifications set up. This project is no longer maintained and I no longer have access to the hardware; however, it looks like the audio stream thread is crashing. I hope that gives you enough to go on!

I'm going to close this as I won't be able to help you troubleshoot, but feel free to clone the repo if you would like to work on this yourself.
